[versions]
android-gradle-plugin = "7.0.4"
agp = "8.4.2"
annotations = "23.0.0"
annotationsVersion = "12.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.2"
activityCompose = "1.9.0"
composeBom = "2024.06.00"
retrofit = "2.9.0"
okhttp = "4.9.3"
gson = "2.9.0"
constraintLayout = "2.1.4"
compose = "1.6.8"  # Update to the latest stable version suitable for your project
material3 = "1.2.1"
materialIconsExtended = "1.6.8"
material = "1.12.0"
navigationCompose = "2.7.7"
ktor = "2.3.10"
lifecycle = "2.8.2"
coroutines = "1.7.3"
serialization = "1.5.1"
mockk = "1.12.0"
coroutinesTest = "1.7.3"
archCoreTesting = "2.2.0"
coil = "2.1.0"
picasso = "2.71828"
room = "2.6.1"
ksp = "1.9.0-1.0.12"
uiTestJunit4 = "1.6.8"
emojicompat = "1.4.0"
carUiLib = "2.6.0"
emoji2 = "1.4.0"
mobile-ffmpeg = "4.4"



[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
intellij-annotations = { module = "com.intellij:annotations", version.ref = "annotationsVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
dexter = { module = "com.karumi:dexter", version = "6.2.3" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
composeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
materialComponents = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
lifecycle-livedata-ktx = "androidx.lifecycle:lifecycle-livedata-ktx:2.8.2"
lifecycle-livedata = "androidx.lifecycle:lifecycle-livedata-ktx:2.8.2"
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
archCoreTesting = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTesting" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version = "1.5.2" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "compose" }
emoji-compat = { group = "androidx.emoji2", name = "emoji2", version.ref = "emojicompat" }
emoji-compat-bundled = { group = "androidx.emoji2", name = "emoji2-bundled", version.ref = "emojicompat" }
car-ui-lib = { group = "com.android.car.ui", name = "car-ui-lib", version.ref = "carUiLib" }
emoji2 = { group = "androidx.emoji2", name = "emoji2", version.ref = "emoji2" }
emoji2-views = { group = "androidx.emoji2", name = "emoji2-views", version.ref = "emoji2" }
emoji2-views-helper = { group = "androidx.emoji2", name = "emoji2-views-helper", version.ref = "emoji2" }
emoji2-emojipicker = { group = "androidx.emoji2", name = "emoji2-emojipicker", version.ref = "emoji2" }
mobile-ffmpeg = { group = "com.arthenica", name = "mobile-ffmpeg-full", version.ref = "mobile-ffmpeg" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }  # Ensure this line is added







